### ISSUE TITLE
GPL v3 is kind of a bummer (my issue, not yours, unless you care...)

### ISSUE THREAD

**Issue by boutell** [mvhenten/ellipsize#2]
You've every right to GPL your module, but be aware that folks won't use it in projects that can't be entirely open-sourced. Please consider a more permissive license if you'd like to see pull requests, bug reports, etc. from folks who are happy to contribute back to the module but can't open-source their entire project.

**Comment by jurom** [comment]
Hi,

I have a very similar problem - but I can't find the new `0.0.3` version published on npm.

**Comment by mvhenten** [comment]
I'll run npm publish once more
