### ISSUE TITLE
incorrect ellipsizing

### ISSUE THREAD

**Issue by thesame** [mvhenten/ellipsize#3]
`ellipsize("a. b", 2).length == 3`

**Comment by mvhenten** [comment]
Hi,
What would be the output you'd expect here?
```
> ellipsize("a. b", 2)
'a.…'
```
Looks correct to me...

**Comment by thesame** [comment]
I expected the output be at most 2 chars long. 3 exceeds the requested length.

**Comment by DetachHead** [comment]
why was this closed? [the documentation here](https://github.com/mvhenten/ellipsize#nb-major-version-change) says that the length should be exactly as specified including the ellipse character
