### ISSUE TITLE
Ellipsize can produce strings longer than max length, even when truncate: true

### ISSUE THREAD

**Issue by justinmchase** [mvhenten/ellipsize#5]
**Example:**
```js
> ellipsize('a - b', 3, { truncate: true }).length
4
```

It appears to happen when one of the chars is exactly max index. I feel like the length of the string should never exceed max.

**Comment by mvhenten** [comment]
This is rather philosophical. e.g. the string is supposed to truncate at MAX_CHARS. Then it adds an ellipsis. This makes the resulting length MAX_CHARS + 1. I do agree that it might have been wiser to stay within the max at all times but this module is in used by others now. it'll require a major version bump or more :)=

**Comment by justinmchase** [comment]
The four hardest problems in computers science:
1. Naming things
2. Cache invalidation
3. Off-by-one errors

Major bump sounds fine, I was hitting errors which were hard to debug until I figured out I needed to use `ellipsisze(str, maxLength - 1, { truncate: true })` everywhere.

**Comment by mvhenten** [comment]
LOL how many times I've used that quote to win an argument. at least I got #1 right. I'll try and carve out sometime tonight and see what I can do.
